import { gql, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import {
  GetAllCountriesDocument,
  GetCountryDocument,
} from "../service/graphql";

const CountryView = () => {
  const { data, loading, error } = useQuery(GetCountryDocument, {
    variables: {
      countryCode: "AD",
    },
  });

  return <>{data?.country?.code}</>;
};

const Home: NextPage = () => {
  const [viewDetail, setViewDetail] = useState(false);
  const { data, loading, error } = useQuery(GetAllCountriesDocument);

  return (
    <>
      <Head>
        <title>Country App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home">
        <h1 className="home__title">Countries</h1>
        {viewDetail && <CountryView />}
        <button onClick={() => setViewDetail(!viewDetail)}>
          {viewDetail ? "Hide" : "View"} detail
        </button>
      </main>
    </>
  );
};

export default Home;
